### ISSUE TITLE
Issue in ORB_SLAM example

### ISSUE THREAD

**Issue by wardazahra** [HITSZ-NRSL/IGLOV#1]
I am facing this issue while running the following example in IGLOV 
ubuntu@ubuntu-VirtualBox:~/catkin_ws/src/IGLOV$ roslaunch orb_slam_2_ros orb_slam2_d435_rgbd_realsense.launch
RLException: [orb_slam2_d435_rgbd_realsense.launch] is neither a launch file in package [orb_slam_2_ros] nor is [orb_slam_2_ros] a launch file name
The traceback for the exception was written to the log file

**Comment by nixwang** [comment]
Have you used "source devel/setup.bash"?

**Comment by zhongtianda** [comment]
There is an error in the README. That should be: roslaunch orb_slam2_ros orb_slam2_d435_rgbd_realsense.launch

**Comment by nixwang** [comment]
Got it!
